[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "spam-eggs"
version = "2025.0.0"
dependencies = [
  "httpx",
  "gidgethub[httpx]>4.0.0",
  "django>2.1; os_name != 'nt'",
  "django>2.0; os_name == 'nt'",
]
requires-python = ">=3.10"
authors = [
  {name = "Ayman Sandouk, email = "ayman_sandouk@uri.edu"},
  {name = "Sarah M Brown, email = "brownsarahm@uri.edu"},
]
maintainers = [
  {name = "Ayman Sandouk, email = "ayman_sandouk@uri.edu"},
  {name = "Sarah M Brown", email = "brownsarahm@uri.edu"}
]
description = ""
readme = "README.md"
license = "MIT"  # or license = {file = "LICENSE.txt"} for legacy declaration
license-files = ["LICEN[CS]E.*"]
keywords = ["benchmark", "machine-learning", "ai", "llm"]


[project.optional-dependencies]
gui = ["PyQt5"]
cli = [
  "rich",
  "click",
  "pyyaml",
  "pandas",
]

[project.urls]
Homepage = "https://example.com"
Documentation = "https://readthedocs.org"
Repository = "https://github.com/ml4sts/benchtools"
"Bug Tracker" = "https://github.com/ml4sts/benchtools/issues"


[project.scripts]
benchtool = "benchtools.cli:benchtool"


